config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, :controllers => {:registrations => "registrations"}
  resources :users
  resources :products

  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  root 'simple_pages#landing_page'
  post 'simple_pages/thank_you'
  get '/products/:id', to: 'products#show'
  post 'payments/create'


  resources :products do
    resources :comments
  end

  resources :orders, only: [:index, :show, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nameofapp</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <!-- navbar start -->
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Boston Boulders", root_path, class: "david-hopkins navbar-brand" %>
      </div><!-- end navbar header -->



      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Products", products_path %></li>
          <li><%= link_to "About", simple_pages_about_path %></li>
          <li><%= link_to "Contact", simple_pages_contact_path %></li>
        </ul>
        <%= form_with(url: products_path, method: 'get', local: true, class:"navbar-form navbar-right") do |form| %>
          <div class="form-group">
            <%= form.text_field :q, id: 'q', value: params[:q], placeholder: "Search", class: "form-control" %>
          </div>
          <%= form.submit 'Search', class:"btn btn-default" %>
        <% end %>
        <% cache do %>
        <ul class="navbar-nav ml-auto nav">
          <% if user_signed_in? %>
          <li>
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class:"btn btn-dark btn-sm") %>
          </li>
          <% else %>
          <li>
            <%= link_to('Login', new_user_session_path, class:"btn btn-dark btn-sm") %>
          </li>
          <% end %>
        </ul>
        <% end %>
      </div><!-- end nav -->
    </div><!-- end nav container -->

  </nav><!-- end navbar -->

    <%= yield %>

    <% if notice %>
      <p id="notice" class="alert alert-primary"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p id="alert" class="alert alert-primary"><%= alert %></p>
    <% end %>

  </body>
  <footer>
    <a href="https://twitter.com/TheDevDave?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @TheDevDave</a>
    <br>
    <div class="fb-like" data-href="https://www.facebook.com/The-Dev-Dave-202199463727881/?modal=admin_todo_tour" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
    <p>&copy; David Hopkins 2018</p>
  </footer>

</html>